export const NBA = [
  {
    id: 0,
    teamName: "Boston Celtics",
    abbreviation: "BOS",
    city: "Boston",
    state: "Massachusetts",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    id: 1,
    teamName: "Brooklyn Nets",
    abbreviation: "BKN",
    city: "Brooklyn",
    state: "New York",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    id: 2,
    teamName: "New York Knicks",
    abbreviation: "NYK",
    city: "New York",
    state: "New York",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    id: 3,
    teamName: "Philadelphia 76ers",
    abbreviation: "PHI",
    city: "Philadelphia",
    state: "Pennsylvania",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    id: 4,
    teamName: "Toronto Raptors",
    abbreviation: "TOR",
    city: "Toronto",
    state: "Ontario",
    conference: "Eastern",
    division: "Atlantic",
  },

  {
    id: 5,
    teamName: "Chicago Bulls",
    abbreviation: "CHI",
    city: "Chicago",
    state: "Illinois",
    conference: "Eastern",
    division: "Central",
  },
  {
    id: 6,
    teamName: "Cleveland Cavaliers",
    abbreviation: "CLE",
    city: "Cleveland",
    state: "Ohio",
    conference: "Eastern",
    division: "Central",
  },
  {
    id: 7,
    teamName: "Detroit Pistons",
    abbreviation: "DET",
    city: "Detroit",
    state: "Michigan",
    conference: "Eastern",
    division: "Central",
  },
  {
    id: 8,
    teamName: "Indiana Pacers",
    abbreviation: "IND",
    city: "Indianapolis",
    state: "Indiana",
    conference: "Eastern",
    division: "Central",
  },
  {
    id: 9,
    teamName: "Milwaukee Bucks",
    abbreviation: "MIL",
    city: "Milwaukee",
    state: "Wisconsin",
    conference: "Eastern",
    division: "Central",
  },

  {
    id: 10,
    teamName: "Atlanta Hawks",
    abbreviation: "ATL",
    city: "Atlanta",
    state: "Georgia",
    conference: "Eastern",
    division: "Southeast",
  },
  {
    id: 11,
    teamName: "Charlotte Hornets",
    abbreviation: "CHA",
    city: "Charlotte",
    state: "North Carolina",
    conference: "Eastern",
    division: "Southeast",
  },
  {
    id: 12,
    teamName: "Miami Heat",
    abbreviation: "MIA",
    city: "Miami",
    state: "Florida",
    conference: "Eastern",
    division: "Southeast",
  },
  {
    id: 13,
    teamName: "Orlando Magic",
    abbreviation: "ORL",
    city: "Orlando",
    state: "Florida",
    conference: "Eastern",
    division: "Southeast",
  },
  {
    id: 14,
    teamName: "Washington Wizards",
    abbreviation: "WAS",
    city: "Washington, D.C.",
    state: "District of Columbia",
    conference: "Eastern",
    division: "Southeast",
  },

  {
    id: 15,
    teamName: "Denver Nuggets",
    abbreviation: "DEN",
    city: "Denver",
    state: "Colorado",
    conference: "Western",
    division: "Northwest",
  },
  {
    id: 16,
    teamName: "Minnesota Timberwolves",
    abbreviation: "MIN",
    city: "Minneapolis",
    state: "Minnesota",
    conference: "Western",
    division: "Northwest",
  },
  {
    id: 17,
    teamName: "Oklahoma City Thunder",
    abbreviation: "OKC",
    city: "Oklahoma City",
    state: "Oklahoma",
    conference: "Western",
    division: "Northwest",
  },
  {
    id: 18,
    teamName: "Portland Trail Blazers",
    abbreviation: "POR",
    city: "Portland",
    state: "Oregon",
    conference: "Western",
    division: "Northwest",
  },
  {
    id: 19,
    teamName: "Utah Jazz",
    abbreviation: "UTA",
    city: "Salt Lake City",
    state: "Utah",
    conference: "Western",
    division: "Northwest",
  },

  {
    id: 20,
    teamName: "Golden State Warriors",
    abbreviation: "GSW",
    city: "San Francisco",
    state: "California",
    conference: "Western",
    division: "Pacific",
  },
  {
    id: 21,
    teamName: "Los Angeles Clippers",
    abbreviation: "LAC",
    city: "Los Angeles",
    state: "California",
    conference: "Western",
    division: "Pacific",
  },
  {
    id: 22,
    teamName: "Los Angeles Lakers",
    abbreviation: "LAL",
    city: "Los Angeles",
    state: "California",
    conference: "Western",
    division: "Pacific",
  },
  {
    id: 23,
    teamName: "Phoenix Suns",
    abbreviation: "PHX",
    city: "Phoenix",
    state: "Arizona",
    conference: "Western",
    division: "Pacific",
  },
  {
    id: 24,
    teamName: "Sacramento Kings",
    abbreviation: "SAC",
    city: "Sacramento",
    state: "California",
    conference: "Western",
    division: "Pacific",
  },

  {
    id: 25,
    teamName: "Dallas Mavericks",
    abbreviation: "DAL",
    city: "Dallas",
    state: "Texas",
    conference: "Western",
    division: "Southwest",
  },
  {
    id: 26,
    teamName: "Houston Rockets",
    abbreviation: "HOU",
    city: "Houston",
    state: "Texas",
    conference: "Western",
    division: "Southwest",
  },
  {
    id: 27,
    teamName: "Memphis Grizzlies",
    abbreviation: "MEM",
    city: "Memphis",
    state: "Tennessee",
    conference: "Western",
    division: "Southwest",
  },
  {
    id: 28,
    teamName: "New Orleans Pelicans",
    abbreviation: "NOP",
    city: "New Orleans",
    state: "Louisiana",
    conference: "Western",
    division: "Southwest",
  },
  {
    id: 29,
    teamName: "San Antonio Spurs",
    abbreviation: "SAS",
    city: "San Antonio",
    state: "Texas",
    conference: "Western",
    division: "Southwest",
  },
];
